/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "AddPath": {                                     "en": "Add the XML path manually from meteoalarm.eu",    "de": "Bitte fügen Sie hier den Pfad zum XML auf meteoalarm.eu ein", "ru": "Пожалуйста, добавьте сюда путь к XML от meteoalarm.eu", "pt": "Por favor, adicione aqui o caminho para o XML de meteoalarm.eu", "nl": "Voeg hier het pad naar de XML van meteoalarm.eu toe", "fr": "Veuillez ajouter ici le chemin d'accès au XML depuis meteoalarm.eu", "it": "Aggiungi qui il percorso dell'XML da meteoalarm.eu", "es": "Agregue aquí la ruta al XML desde meteoalarm.eu", "pl": "Dodaj tutaj ścieżkę do XML z meteoalarm.eu",      "zh-cn": "请在这里添加meteoalarm.eu的XML路径"},
    "instruction": {                                 "en": "For help, please check the description here: https://github.com/jack-blackson/ioBroker.meteoalarm", "de": "Für Hilfe, besuchen Sie: https://github.com/jack-blackson/ioBroker.meteoalarm", "ru": "Для помощи, пожалуйста, проверьте описание здесь: https://github.com/jack-blackson/ioBroker.meteoalarm", "pt": "Para obter ajuda, por favor, verifique a descrição aqui: https://github.com/jack-blackson/ioBroker.meteoalarm", "nl": "Raadpleeg de beschrijving hier voor hulp: https://github.com/jack-blackson/ioBroker.meteoalarm", "fr": "Pour obtenir de l'aide, veuillez consulter la description ici: https://github.com/jack-blackson/ioBroker.meteoalarm", "it": "Per assistenza, controlla la descrizione qui: https://github.com/jack-blackson/ioBroker.meteoalarm", "es": "Para obtener ayuda, consulte la descripción aquí: https://github.com/jack-blackson/ioBroker.meteoalarm", "pl": "Aby uzyskać pomoc, sprawdź opis tutaj: https://github.com/jack-blackson/ioBroker.meteoalarm", "zh-cn": "如需帮助，请查看以下说明：https：//github.com/jack-blackson/ioBroker.meteoalarm"},
    "country": {                                     "en": "Country",                                         "de": "Land",                                            "ru": "Страна",                                          "pt": "País",                                            "nl": "Land",                                            "fr": "Pays",                                            "it": "Nazione",                                         "es": "País",                                            "pl": "Kraj",                                            "zh-cn": "国家"},
    "loadRegions": {                                 "en": "Load regions",                                    "de": "Regionen laden",                                  "ru": "Загрузить регионы",                               "pt": "Carregar regiões",                                "nl": "Laad regio's",                                    "fr": "Charger les régions",                             "it": "Carica regioni",                                  "es": "Regiones de carga",                               "pl": "Załaduj regiony",                                 "zh-cn": "加载区域"},
    "AddLinkManually": {                             "en": "Get the link from the meteoalarm website",        "de": "Holen Sie sich den Link von der Meteoalarm-Website", "ru": "Получить ссылку с сайта meteoalarm",              "pt": "Obtenha o link no site meteoalarm",               "nl": "Download de link van de meteoalarm-website",      "fr": "Obtenez le lien sur le site Web de meteoalarm",   "it": "Ottieni il link dal sito Web meteoalarm",         "es": "Obtenga el enlace del sitio web meteoalarm",      "pl": "Uzyskaj link ze strony meteoalarm",               "zh-cn": "从meteoalarm网站获取链接"},
    "AddLinkAutomatically": {                        "en": "Generate the link by choosing country and region", "de": "Generieren Sie den Link, indem Sie Land und Region auswählen", "ru": "Создайте ссылку, выбрав страну и регион",         "pt": "Gere o link escolhendo país e região",            "nl": "Genereer de link door land en regio te kiezen",   "fr": "Générez le lien en choisissant le pays et la région", "it": "Genera il link scegliendo Paese e regione",       "es": "Genere el enlace eligiendo país y región",        "pl": "Wygeneruj link, wybierając kraj i region",        "zh-cn": "通过选择国家和地区来生成链接"},
    "instructionLoading": {                          "en": "Please select country first and click: load region", "de": "Bitte wählen Sie zuerst das Land aus und klicken Sie auf: Region laden", "ru": "Пожалуйста, сначала выберите страну и нажмите: загрузить регион", "pt": "Selecione primeiro o país e clique em: carregar região", "nl": "Selecteer eerst het land en klik op: laad regio", "fr": "Veuillez d'abord sélectionner le pays et cliquez sur: charger la région", "it": "Seleziona prima il paese e fai clic su: carica regione", "es": "Seleccione primero el país y haga clic en: cargar región", "pl": "Najpierw wybierz kraj i kliknij: wczytaj region", "zh-cn": "请首先选择国家，然后单击：加载区域"},
};